---
- name: Deploying Nginx
  hosts: all
  vars_files:
    - vault.yaml

  tasks:
    #    - name: Subscribe machine
    #      community.general.redhat_subscription:
    #        state: present
    #        username: "{{ vault.rhsm.user }}"
    #        password: "{{ vault.rhsm.pass }}"

    - name: Subscribe machine
      no_log: true
      shell: "subscription-manager register --username {{ vault.rhsm.user}} --password {{ vault.rhsm.pass }}"

    - name: Ensure Nginx is installed
      ansible.builtin.package:
        state: present
        name: nginx

    - name: Ensure Nginx is running
      ansible.builtin.systemd:
        state: started
        name: nginx

    - name: Ensure firewall is open for HTTP traffic
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled

    - name: Change landing page text
      ansible.builtin.replace:
        path: /usr/share/nginx/html/index.html
        regexp: 'Red Hat Enterprise Linux <strong>Test Page<\/strong>'
        replace: 'Ansible <3 Terraform'
