---
- name: Terraforming with Ansible
  hosts: all

  tasks:
    - name: Run terraform
      cloud.terraform.terraform:
        project_path: "{{ playbook_dir }}/terraform/"
        state: present
        force_init: true
