---
- name: Terraforming with Ansible
  hosts: all

  tasks:
    - name: Find out playbook's path
      shell: pwd
      register: playbook_path_output
    - debug: var=playbook_path_output.stdout
            
    - name: Find out playbook's dir contents
      shell: "ls -lah"
      register: playbook_path_output
    - debug: var=playbook_path_output.stdout

    - name: Run terraform
      cloud.terraform.terraform:
        project_path: "{{ playbook_dir }}/terraform/"
        state: present
        force_init: true
