---
- name: Terraforming with Ansible
  hosts: all
  vars:
    tf_vars:
      machines:
        machine1:
          vCPUs: 2
          memory: 1024
        machine2:
          vCPUs: 1
          memory: 512

  tasks:
    - name: Clone a github repository
      ansible.builtin.git:
        repo: https://github.com/lbac-redhat/terraforming-with-ansible.git
        dest: repo
        clone: true

    - name: Run terraform
      cloud.terraform.terraform:
        project_path: repo/terraform
        state: present
        force_init: true
        complex_vars: true
        variables: "{{ tf_vars }}"
