---
- name: Terraforming with Ansible
  hosts: all
  vars:
    tf_vars:
      machines:
        machine1:
          vCPUs: 2
          memory: 1024
        machine2:
          vCPUs: 1
          memory: 512

  tasks:
    - name: Clone a github repository
      ansible.builtin.git:
        repo: https://github.com/lbac-redhat/terraforming-with-ansible.git
        dest: repo
        clone: true

    - name: Run terraform plan
      cloud.terraform.terraform:
        project_path: repo/terraform
        state: planned
        plan_file: tf.plan
        force_init: true
        complex_vars: true
        variables: "{{ tf_vars }}"
      # check_mode: false
      register: tf_plan

    - name: Print plan
      debug:
        msg: "{{ tf_plan.stdout_lines }}"

    - name: Execute plan
      cloud.terraform.terraform:
        project_path: repo/terraform
        state: present
        plan_file: tf.plan
