---
- name: Terraforming with Ansible
  hosts: all

  tasks:
    - name: Clone a github repository
      ansible.builtin.git:
        repo: https://github.com/lbac-redhat/terraforming-with-ansible.git
        dest: repo
        clone: true

    - name: Run terraform
      cloud.terraform.terraform:
        project_path: repo/terraform
        state: present
        force_init: true
